baseurl: https://casualcoding.netlify.app/
languageCode: en-us
title: Ezra Citrons Website
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
enableEmoji: TRUE
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
  
menu:
  main:
    - name: CV
      url: /main_page/cv/
      
      
    - name: Resources
      url: /main_page/resources
      
    - name: About
      url: /main_page/about
      
    - name: GitHub
      url: https://github.com/citrez
      
      
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
